


export const ExperienceList = [
  {
    id: 1,
    type: "education",
    school_company: " Ramrajya Vidyalay, Pune , Maharashtra ",
    date: "2015",
    degree_position: "SSC",
    work_on: "",
    percentage: 93.20,
    website: "",
  },
  {
    id: 2,
    type: "education",
    school_company: "MES Abasaheb Garware College, Pune, Maharashtra",
    date: "2015-2017",
    degree_position: "HSC",
    work_on: "Science",
    percentage: 77.69,
    website: "https://garwarecollege.mespune.in/",
  },
  {
    id: 3,
    type: "education",
    school_company: "MES Abasaheb Garware College, Pune, Maharashtra",
    date: "2017-2020",
    degree_position: "B.Sc",
    work_on: "Computer Science",
    percentage: 78.25,
    website: "https://garwarecollege.mespune.in/",
  },
  {
    id: 4,
    type: "education",
    school_company: "Fergusson College, Pune, Maharashtra",
    date: "2020-2022",
    degree_position: "M.Sc",
    work_on: "Computer Application",
    percentage: 84.25,
    website: "https://fccollege.in/",
  },
  {
    id: 5,
    type: "work",
    school_company: "Intern at Sciqus Infotech  Pune , Maharashtra",
    subtitle: " Pune , Maharashtra",
    date: "March 2022 - July 2022",
    degree_position: "Intern",
    work_on: "Worked on .Net Framework",
    website: "http://sciqusInfotech.com/",
  },
  {
    id: 6,
    type: "work",
    school_company: "Software Engineer Trainee at Siemens Technology",
    subtitle: "Baner, Pune , India",
    date: "June 2022 - Feb 2023",
    degree_position: "Software Engineer Trainee",
    work_on: "Learned and upskilled into front-end technologies like HTML, CSS, JavaScript, React ,MUI",
    website: "https://www.siemens.com/",
  },
];